### ISSUE TITLE
I reached level 1 three times???

### ISSUE THREAD

**Issue by amanemisa** [DankMemer/dank-memer-suggestions-and-bugs#203] opened 2020-05-04 20:54 UTC
I was just using the Dank Memer bot on my server, as I do everyday, and I received a message from the bot that I leveled up. I think 'nice' then go back to my server to keep using commands, and I receive another DM. I had reached level 1 again and I thought 'that's weird, didn't I just reach level 1??'. I check my balance and 10,000 coins had been added to my account balance since I reached level 1 twice (you get 5k from reaching level 1 ONCE). I keep using commands in my server and had reached level 1 again. After that, I stopped reaching the same level over and over again. I don't know what I did to accidentally trigger this bug since I was just cycling through currency commands as usual (search, postmemes, and beg). 

Here is a screenshot of the DMs with Dank Memer where I _somehow_ reached the same level 3 times...

<img width="969" alt="Screen Shot 2020-05-04 at 4 41 59 PM" src="https://user-images.githubusercontent.com/64809843/81012552-baf97200-8e27-11ea-9c2c-19769b4fac31.png">

**Comment by thewilloftheshadow** [comment] 2020-05-04 21:35
Duplicate of #191

**Comment by SothePerson** [comment] 2020-05-05 16:41
It is a common glitch. I'm pretty sure the dank memer team is fixing it rn. It also happened to me.

**Closed** 2020-05-09 19:07 UTC
Labels: bug, duplicate
