### ISSUE TITLE
Double Down in "pls blackjack"

### ISSUE THREAD

**Issue by loser7007** [DankMemer/dank-memer-suggestions-and-bugs#722] opened 2020-06-12 23:17 UTC
How about adding a feature with pls blackjack that allows you to double down?
double down is a real blackjack feature that I think could improve the blackjacking experience. by typing d or dd your bet will double and also draw you a card. if you win you will gain twice your original bet, and if you lose you will lose double your original bet.  
I think this feature will make playing pls blackjack a little better and I don't think this will break the game because it exists in real life and casinos are still in business.
please consider adding this :)

**Comment by oliverysfx** [comment] 2020-06-13 06:46
this is a duplicate of one that has been closed, so close this b4 melmsie wastes his time reading duplicate suggestions

**Closed** 2020-06-13 15:39 UTC
Labels: enhancement request
