### ISSUE TITLE
remove passive users off the pls rich leaderboard

### ISSUE THREAD

**Issue by oliverysfx** [DankMemer/dank-memer-suggestions-and-bugs#584] opened 2020-06-03 07:40 UTC
**Is your feature request related to a problem? Please describe.**
It's really frustrating when you go into a server that you got from a friend that's called a robbing server just to find that everyone on the 10 pages of pls rich is sitting on passive

**Describe the solution you'd like**
remove passive users off pls rich

**Describe alternatives you've considered**
none

**Additional context**
also just wondering, why does the last page of pls rich show less than 5 users

**Comment by Wise2006** [comment] 2020-06-03 12:57
Duplicate of #221 

As clearly mentioned by Mel, it's a rich leaderboard and not 'users to rob' leaderboard.
Also, maybe there aren't enough rich users in the server.

**Comment by oliverysfx** [comment] 2020-06-03 13:13
but then that would be very incovenient for large servers, where basically the whole pls rich is full of passive users

**Comment by melmsie** [comment] 2020-06-03 13:39
For the last time, we're not removing passive users off rich. Any further requests for this will be instantly closed.

**Closed by melmsie** 2020-06-03 13:39 UTC
Labels: enhancement request
