### ISSUE TITLE
Stocks/Stonks command

### ISSUE THREAD

**Issue by Lelmaster3457** [DankMemer/dank-memer-suggestions-and-bugs#145] opened 2020-04-20 13:49 UTC
**Is your feature request related to a problem? Please describe.**
No it isn't, I just think it's a cool idea.
**Describe the solution you'd like**
I think it would be cool if there was a stocks command that lets you invest in 5 different types of stocks that change every 10 minutes or so using a rng. The idea is to invest in it while it is low, and then get your stocks back when they go up.
**Describe alternatives you've considered**
I haven't really thought of any alternatives, sorry.
**Additional context**
Can you send me an email or something when you see this or if you like the idea? Just like a general update on what is going on for this idea. My email is 8bitOmpa@gmail.com if you could send there.

**Comment by melmsie** [comment] 2020-04-20 13:53
Third duplicate of this exact thing.

**Closed by melmsie** 2020-04-20 13:53 UTC
Labels: enhancement
