### ISSUE TITLE
I was about to post a suggestion and saw that the link in pls suggest leads to 404

### ISSUE THREAD

**Issue by SergeTFM** [DankMemer/dank-memer-suggestions-and-bugs#580] opened 2020-06-03 05:02 UTC
**Describe the bug**
the link in pls suggest leads to 404

**To Reproduce**
1. run pls suggest
2. Click on the link {https://github.com/DankMemer/dank-memer-suggestions-n%27-bugs}
3. See 404
4. Actual link is https://github.com/DankMemer/dank-memer-suggestions-and-bugs theres "n%27" instead of "and" in the link

**Expected behavior**
The link should link to the github as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/50763771/83597629-779e3a80-a570-11ea-8a40-d40a2bcd9b4d.png)
First link is actual link second link is the one in the embed

**Additional context**

**Comment by oliverysfx** [comment] 2020-06-03 07:49
duplicate of #551

**Closed** 2020-06-05 17:02 UTC
Labels: bug
