### ISSUE TITLE
naming your pet to a role ping can ping roles

### ISSUE THREAD

**Issue by damboi38** [DankMemer/dank-memer-suggestions-and-bugs#985] opened 2020-07-06 14:06 UTC
**Describe the bug**
- If i name my pet to a role mention, and i interact with the pet, it mentions the role, even if the roles not mentionable.

**Expected behavior**
- It should'nt ping the role like the other commands

![image](https://user-images.githubusercontent.com/65500334/86602896-20531600-bfc5-11ea-9270-be99b9dbb4b7.png)

**Comment by andrewisaboomer** [comment] 2020-07-06 14:29
a dupe of another bug i think

**Comment by melmsie** [comment] 2020-07-06 14:32
fixed next update

**Closed by melmsie** 2020-07-06 14:32 UTC
Labels: bug

**Comment by andrewisaboomer** [comment] 2020-07-06 14:34
#868 
same thing
