### ISSUE TITLE
calling police bug while being bankrobbed 

### ISSUE THREAD

**Issue by pseudocoder10** [DankMemer/dank-memer-suggestions-and-bugs#876] opened 2020-06-26 12:45 UTC
**Describe the bug**
Someone tried to bankrob me and then started a tic tac toe game immediately after that. When I tried to use my cellphone, it didnt work because the bot thought I replied to the tic tac toe game

**Expected behavior**
calling police should have worked

**Screenshots**
[ss1](https://i.imgur.com/AInhwJP.png)
[ss2](https://i.imgur.com/Zk0bQAw.png)

**Your User ID**
515920333623263252

**Comment by PhantomFrenzy151** [comment] 2020-06-26 21:36
This is a known "bug". This is included in the strategy of bank robbing. both ttt and fight are commands that do this.

**Comment by oliverysfx** [comment] 2020-06-28 04:35
this is not a bug, and this is in fact a duplicate, please close this before melmsie wastes time reading this

**Closed** 2020-06-30 23:12 UTC
Labels: bug
