### ISSUE TITLE
Pls quest choose not working

### ISSUE THREAD

**Issue by DrKami** [DankMemer/dank-memer-suggestions-and-bugs#961] opened 2020-07-03 20:07 UTC
After waiting to reset quest (in this case, chronic gambler quest) in currency system, I did pls quest choose chronic gambler. The bot replies that I have to wait 0 seconds to do this quest again. Bug repeatedly pops up for this quest no matter how long I wait.

**To Reproduce**
1. Go to any discord server with bot
2. Type 'pls quest choose chronic gambler'
3. Bot replies with 'You've already completed this quest! You gotta wait **0 seconds** until you can do it again lol'

**Expected behavior**
Should either activate quest or reply with amount of time to wait

**Screenshots**
![Screen Shot 2020-07-03 at 1 04 23 PM](https://user-images.githubusercontent.com/67804873/86495371-f502c980-bd2d-11ea-9dfd-0287ffea5bbe.png)

**Comment by andrewisaboomer** [comment] 2020-07-03 23:27
im pretty sure thats a dupe of another bug, its caused by u doing the quest before the update that allowed you to redo quests was added

**Comment by oliverysfx** [comment] 2020-07-04 09:03
yeah

**Closed** 2020-07-06 00:45 UTC
Labels: bug

**Comment by darqlt** [comment] 2020-07-24 09:02
Any solution for this? I have the same issue
