### ISSUE TITLE
Passive mode pls gift

### ISSUE THREAD

**Issue by MegusHooIT** [DankMemer/dank-memer-suggestions-and-bugs#501] opened 2020-06-01 05:51 UTC
I'm always frustrated when I want to gift items or give money, but I'm in passive mode. I would turn off passive mode to gift, then get robbed over and over until I'm dirt poor.

I want pls gift and pls share to be able to be used in passive mode. This makes sense, because you are actually losing an item or money, and not gaining any. You're still passive, you just gave that one dude 50 pieces of fresh bread for the memes, or shared someone 10k because you borrowed 5k from them a week ago.

Have a good day.

**Comment by Wise2006** [comment] 2020-06-01 05:53
Do you mean that you can't receive coins/items and only share?
Wouldn't that be confusing?

**Comment by Wise2006** [comment] 2020-06-01 05:55
Duplicate of #489

**Comment by melmsie** [comment] 2020-06-01 14:56
Interact with no one, or interact with everyone.

**Closed by melmsie** 2020-06-01 14:56 UTC
Labels: enhancement request

**Comment by psprojectC** [comment] 2020-06-09 11:26
"iNtErAcT WiTh nO OnE, oR InTeRaCt wItH EvErYoNe." This nonsense of a defense falls apart if you consider that you can use pinkphallicobject-s in passive.

**Comment by melmsie** [comment] 2020-06-09 13:41
@psprojectC are you really advocating that we also don't let people send pink phallics in passive? You think sending a single tiny item at a time is the same as sharing as many coins or items as you want? Found the ACTUAL nonsensical argument

**Comment by babycreeper189** [comment] 2020-06-18 21:44
lmfao
